### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by megoRU** [pvhil/FaceItDiscord#2]
Can be done without checks
https://github.com/pvhil/FaceItDiscord/blob/2a375bbdeea7b7606c751b8396a6e678ce0c8f24/src/main/java/DiscordMessage.java#L1386-L1415

Wouldn't it be easier to do it this way:

```faceitLevelPNG = "https://raw.githubusercontent.com/pvhil/FaceItDiscord/master/src/main/resources/images/" + String.valueOf(faceitAPI.faceitLevel) + ".png";```

P. S. 
You also have a different case of the file extension in the folder where the pictures are located ```src/main/resources/images```. In Windows, there is a conflict because of this, I did not make a pull request.

**Comment by pvhil** [comment]
Hello, first thanks for your message! Never thought somebody would contribute to this project.
I will implement this asap.

**Comment by megoRU** [comment]
I was happy to help
