### ISSUE TITLE
Optimization v2

### ISSUE THREAD

**Issue by megoRU** [pvhil/FaceItDiscord#3]
Lots of code for maps checks:

https://github.com/pvhil/FaceItDiscord/blob/b067637b429edd3b823fe3d0ce7368d812580429/src/main/java/DiscordMessage.java#L781
//class fields
`private static final String[] MAPS = {"dust2", "mirage", "train", "cache", "overpass", "vertigo", "inferno", "nuke"};`

//over if checks
`boolean containsMap = Arrays.asList(MAPS).contains(savedMap.toLowerCase(Locale.ROOT));`

```
if (args[1].equalsIgnoreCase("last") || args[1].equalsIgnoreCase("latest") || containsMap) { 
//some code
}
```

P. S.
I can't cover the entire hierarchy/architecture of your code in a couple of minutes, but I think it will give you food for thought.
Probably my option is not very reliable, but in my case it works pretty well.

**Comment by pvhil** [comment]
I appreciate your work. The code looks like a mess because it was my first ever complete Java project. I will keep your optimizations in mind when im rewriting the code. Thanks :)
